using System;
using System.Collections.Generic;
using System.Text;

namespace NumberValidators.Utils.GBT
{
    /// <summary>
    /// 世界各国和地区名称代码
    /// </summary>
    public class NationCode
    {
        /// <summary>
        /// 世界各国和地区名称代码基础数据 （GB/T 2659-2000）
        /// </summary>
        public static readonly NationCode[] NationCodes = new NationCode[] {
            #region 基础数据
            new NationCode{ChineseAbbr="阿富汗",EnglishAbbr="AFGHANISTAN",TwoCharCode="AF",ThreeCharCode="AFG",DigitalCode="004",FullNameOfCHS="阿富汗伊斯兰国",FullNameOfENG="Islamic State ofAfghanistan"},
            new NationCode{ChineseAbbr="阿尔巴尼亚",EnglishAbbr="ALBANIA",TwoCharCode="AL",ThreeCharCode="ALB",DigitalCode="008",FullNameOfCHS="阿尔马尼亚共和国",FullNameOfENG="Republic ofAlbania"},
            new NationCode{ChineseAbbr="阿尔及利亚",EnglishAbbr="ALGERIA",TwoCharCode="DZ",ThreeCharCode="DZA",DigitalCode="012",FullNameOfCHS="阿尔及利亚民主人民共和国",FullNameOfENG="Democratic People's Republic of Algeria"},
            new NationCode{ChineseAbbr="美属萨摩亚",EnglishAbbr="AMERICAN SAMOA",TwoCharCode="AS",ThreeCharCode="ASM",DigitalCode="016",FullNameOfCHS="美属萨摩亚",FullNameOfENG="American Samoa"},
            new NationCode{ChineseAbbr="安道尔",EnglishAbbr="ANDORRA",TwoCharCode="AD",ThreeCharCode="AND",DigitalCode="020",FullNameOfCHS="安道尔公国",FullNameOfENG="Principality of Andorra"},
            new NationCode{ChineseAbbr="安哥拉",EnglishAbbr="ANGOLA",TwoCharCode="AO",ThreeCharCode="AGO",DigitalCode="024",FullNameOfCHS="安哥拉共和国",FullNameOfENG="Republic of Angola"},
            new NationCode{ChineseAbbr="安圭拉",EnglishAbbr="ANGUILLA",TwoCharCode="AI",ThreeCharCode="AIA",DigitalCode="660",FullNameOfCHS="安圭拉",FullNameOfENG="Anguilla"},
            new NationCode{ChineseAbbr="南极洲",EnglishAbbr="ANTARCTICA",TwoCharCode="AQ",ThreeCharCode="ATA",DigitalCode="010",FullNameOfCHS="南极洲",FullNameOfENG="Antarctica"},
            new NationCode{ChineseAbbr="安提瓜和巴布达",EnglishAbbr="ANTIGUA AND BARBUDA",TwoCharCode="AG",ThreeCharCode="ATG",DigitalCode="028",FullNameOfCHS="安提瓜和巴布达",FullNameOfENG="Antigua and Barbuda"},
            new NationCode{ChineseAbbr="阿根廷",EnglishAbbr="ARGENTINA",TwoCharCode="AR",ThreeCharCode="ARG",DigitalCode="032",FullNameOfCHS="阿根廷共和国",FullNameOfENG="Republic of Argentina"},
            new NationCode{ChineseAbbr="亚美尼亚",EnglishAbbr="ARMENIA",TwoCharCode="AM",ThreeCharCode="ARM",DigitalCode="051",FullNameOfCHS="亚美尼亚共和国",FullNameOfENG="Republic of Armenia"},
            new NationCode{ChineseAbbr="阿鲁巴",EnglishAbbr="ARUBA",TwoCharCode="AW",ThreeCharCode="ABW",DigitalCode="533",FullNameOfCHS="阿鲁巴",FullNameOfENG="Aruba"},
            new NationCode{ChineseAbbr="澳大利亚",EnglishAbbr="AUSTRALIA",TwoCharCode="AU",ThreeCharCode="AUS",DigitalCode="036",FullNameOfCHS="澳大利亚联邦",FullNameOfENG="Commonwealth ofAustralia"},
            new NationCode{ChineseAbbr="奥地利",EnglishAbbr="AUSTRIA",TwoCharCode="AT",ThreeCharCode="AUT",DigitalCode="040",FullNameOfCHS="奥地利共和国",FullNameOfENG="Republic of Austria"},
            new NationCode{ChineseAbbr="阿塞拜疆",EnglishAbbr="AZERBAIJAN",TwoCharCode="AZ",ThreeCharCode="AZE",DigitalCode="031",FullNameOfCHS="阿塞拜疆共和国",FullNameOfENG="Republic ofAzerbaijan"},
            new NationCode{ChineseAbbr="巴哈马",EnglishAbbr="BAHAMAS",TwoCharCode="BS",ThreeCharCode="BHS",DigitalCode="044",FullNameOfCHS="巴哈马联邦",FullNameOfENG="Commonwealth of theBahamas"},
            new NationCode{ChineseAbbr="巴林",EnglishAbbr="BAHRAIN",TwoCharCode="BH",ThreeCharCode="BHR",DigitalCode="048",FullNameOfCHS="巴林国",FullNameOfENG="State of Bahrain"},
            new NationCode{ChineseAbbr="孟加拉国",EnglishAbbr="BANGLADESH",TwoCharCode="BD",ThreeCharCode="BGD",DigitalCode="050",FullNameOfCHS="孟加拉人民共和国",FullNameOfENG="People's Republicof Bangladesh"},
            new NationCode{ChineseAbbr="巴巴多斯",EnglishAbbr="BARBADOS",TwoCharCode="BB",ThreeCharCode="BRB",DigitalCode="052",FullNameOfCHS="巴巴多斯",FullNameOfENG="Barbados"},
            new NationCode{ChineseAbbr="白俄罗斯",EnglishAbbr="BELARUS",TwoCharCode="BY",ThreeCharCode="BLR",DigitalCode="112",FullNameOfCHS="白俄罗斯共和国",FullNameOfENG="Republic of Belarus"},
            new NationCode{ChineseAbbr="比利时",EnglishAbbr="BELGIUM",TwoCharCode="BE",ThreeCharCode="BEL",DigitalCode="056",FullNameOfCHS="比利时王国",FullNameOfENG="Kingdom of belgium"},
            new NationCode{ChineseAbbr="伯利兹",EnglishAbbr="BELIZE",TwoCharCode="BZ",ThreeCharCode="BLZ",DigitalCode="084",FullNameOfCHS="伯利兹",FullNameOfENG="Belize"},
            new NationCode{ChineseAbbr="贝宁",EnglishAbbr="BENIN",TwoCharCode="BJ",ThreeCharCode="BEN",DigitalCode="204",FullNameOfCHS="贝宁共和国",FullNameOfENG="Republic of Benin"},
            new NationCode{ChineseAbbr="百慕大",EnglishAbbr="BERMUDA",TwoCharCode="BM",ThreeCharCode="BMU",DigitalCode="060",FullNameOfCHS="百慕大群岛",FullNameOfENG="Bermuda Islands"},
            new NationCode{ChineseAbbr="不丹",EnglishAbbr="BHUTAN",TwoCharCode="BT",ThreeCharCode="BTN",DigitalCode="064",FullNameOfCHS="不丹王国",FullNameOfENG="Kingdom of Bhutan"},
            new NationCode{ChineseAbbr="玻利维亚",EnglishAbbr="BOLIVIA",TwoCharCode="BO",ThreeCharCode="BOL",DigitalCode="068",FullNameOfCHS="玻利维亚共和国",FullNameOfENG="Republic of Bolivia"},
            new NationCode{ChineseAbbr="波黑",EnglishAbbr="BOSNIA ANDHERZEGOVINA",TwoCharCode="BA",ThreeCharCode="BIH",DigitalCode="070",FullNameOfCHS="波斯尼亚和黑塞哥维那",FullNameOfENG="Bosnia andHerzegovina"},
            new NationCode{ChineseAbbr="博茨瓦纳",EnglishAbbr="BOTSWANA",TwoCharCode="BW",ThreeCharCode="BWA",DigitalCode="072",FullNameOfCHS="博茨瓦纳共和国",FullNameOfENG="Republic ofBotswana"},
            new NationCode{ChineseAbbr="布维岛",EnglishAbbr="BOUVET ISLAND",TwoCharCode="BV",ThreeCharCode="BVT",DigitalCode="074",FullNameOfCHS="布维岛",FullNameOfENG="Bouvet Island"},
            new NationCode{ChineseAbbr="巴西",EnglishAbbr="BRAZIL",TwoCharCode="BR",ThreeCharCode="BRA",DigitalCode="076",FullNameOfCHS="巴西联邦共和国",FullNameOfENG="Federative Republicof Brazil"},
            new NationCode{ChineseAbbr="英属印度洋领土",EnglishAbbr="BRITISH INDIAN OCEANTER-RITORY",TwoCharCode="IO",ThreeCharCode="IOT",DigitalCode="086",FullNameOfCHS="英属印度洋领土",FullNameOfENG="British IndianOcean Territory"},
            new NationCode{ChineseAbbr="文莱",EnglishAbbr="BRUNEI DARUSSALAM",TwoCharCode="BN",ThreeCharCode="BRN",DigitalCode="096",FullNameOfCHS="文莱达鲁萨兰国",FullNameOfENG="Brunei Darussalam"},
            new NationCode{ChineseAbbr="保加利亚",EnglishAbbr="BULGARIA",TwoCharCode="BG",ThreeCharCode="BGR",DigitalCode="100",FullNameOfCHS="保加利亚共和国",FullNameOfENG="Republic ovBulgaria"},
            new NationCode{ChineseAbbr="布基纳法索",EnglishAbbr="BURKINA FASO",TwoCharCode="BF",ThreeCharCode="BFA",DigitalCode="854",FullNameOfCHS="布基纳法索",FullNameOfENG="Burkina Faso"},
            new NationCode{ChineseAbbr="布隆迪",EnglishAbbr="BURUNDI",TwoCharCode="BI",ThreeCharCode="BDI",DigitalCode="108",FullNameOfCHS="布隆迪共和国",FullNameOfENG="Republic of Burundi"},
            new NationCode{ChineseAbbr="柬埔寨",EnglishAbbr="CAMBODIA",TwoCharCode="KH",ThreeCharCode="KHM",DigitalCode="116",FullNameOfCHS="柬埔寨王国",FullNameOfENG="Kingdom of Cambodia"},
            new NationCode{ChineseAbbr="喀麦隆",EnglishAbbr="CAMEROON",TwoCharCode="CM",ThreeCharCode="CMR",DigitalCode="120",FullNameOfCHS="喀麦隆共和国",FullNameOfENG="Republic of Cameroon"},
            new NationCode{ChineseAbbr="加拿大",EnglishAbbr="CANADA",TwoCharCode="CA",ThreeCharCode="CAN",DigitalCode="124",FullNameOfCHS="加拿大",FullNameOfENG="Canada"},
            new NationCode{ChineseAbbr="佛得角",EnglishAbbr="CAPE VERDE",TwoCharCode="CV",ThreeCharCode="CPV",DigitalCode="132",FullNameOfCHS="佛得角共和国",FullNameOfENG="Republic of Cape Verde"},
            new NationCode{ChineseAbbr="开曼群岛",EnglishAbbr="CAYMAN ISLANDS",TwoCharCode="KY",ThreeCharCode="CYM",DigitalCode="136",FullNameOfCHS="开曼群岛",FullNameOfENG="Cayman Islands"},
            new NationCode{ChineseAbbr="中非",EnglishAbbr="CENTRAL AFRICA",TwoCharCode="CF",ThreeCharCode="CAF",DigitalCode="140",FullNameOfCHS="中非共和国",FullNameOfENG="Central African Republic"},
            new NationCode{ChineseAbbr="乍得",EnglishAbbr="CHAD",TwoCharCode="TD",ThreeCharCode="TCD",DigitalCode="148",FullNameOfCHS="乍得共和国",FullNameOfENG="Republic of Chad"},
            new NationCode{ChineseAbbr="智利",EnglishAbbr="CHILE",TwoCharCode="CL",ThreeCharCode="CHL",DigitalCode="152",FullNameOfCHS="智利共和国",FullNameOfENG="Republic of Chile"},
            new NationCode{ChineseAbbr="中国",EnglishAbbr="CHINA",TwoCharCode="CN",ThreeCharCode="CHN",DigitalCode="156",FullNameOfCHS="中华人民共和国",FullNameOfENG="People's Republic of China"},
            new NationCode{ChineseAbbr="香港",EnglishAbbr="HONG KONG",TwoCharCode="HK",ThreeCharCode="HKG",DigitalCode="344",FullNameOfCHS="香港",FullNameOfENG="Hong Kong"},
            new NationCode{ChineseAbbr="澳门",EnglishAbbr="MACAU",TwoCharCode="MO",ThreeCharCode="MAC",DigitalCode="446",FullNameOfCHS="澳门",FullNameOfENG="Macau"},
            new NationCode{ChineseAbbr="台湾",EnglishAbbr="TAIWAN, PROVINCE OF CHINA",TwoCharCode="TW",ThreeCharCode="TWN",DigitalCode="158",FullNameOfCHS="中国台湾",FullNameOfENG="Taiwan, Province of China"},
            new NationCode{ChineseAbbr="圣诞岛",EnglishAbbr="CHRISTMAS ISLAND",TwoCharCode="CS",ThreeCharCode="CSR",DigitalCode="162",FullNameOfCHS="圣诞岛",FullNameOfENG="Christmas Island"},
            new NationCode{ChineseAbbr="科科斯(基林)群岛",EnglishAbbr="COCOS(KEELING)ISLANDS",TwoCharCode="CC",ThreeCharCode="CCK",DigitalCode="166",FullNameOfCHS="科科斯(基林)群岛",FullNameOfENG="Cocos(Keeling)Islands"},
            new NationCode{ChineseAbbr="哥伦比亚",EnglishAbbr="COLOMBIA",TwoCharCode="Co",ThreeCharCode="COL",DigitalCode="170",FullNameOfCHS="哥伦比亚共和国",FullNameOfENG="Republic ofColombia"},
            new NationCode{ChineseAbbr="科摩罗",EnglishAbbr="COMOROS",TwoCharCode="KM",ThreeCharCode="COM",DigitalCode="174",FullNameOfCHS="科摩罗伊斯兰联邦共和国",FullNameOfENG="FederalIslamic Republic of the Co-moros"},
            new NationCode{ChineseAbbr="刚果（布）",EnglishAbbr="CONGO",TwoCharCode="CG",ThreeCharCode="COG",DigitalCode="178",FullNameOfCHS="刚果共和国",FullNameOfENG="Republic of Congo"},
            new NationCode{ChineseAbbr="刚果（金）",EnglishAbbr="CONGO, THE DEMOCRATICREPUBLIC OF THE",TwoCharCode="CD",ThreeCharCode="COD",DigitalCode="180",FullNameOfCHS="刚果民主共和国",FullNameOfENG="Democratic Republicof Congo"},
            new NationCode{ChineseAbbr="库克群岛",EnglishAbbr="COOK ISLANDS",TwoCharCode="CK",ThreeCharCode="COK",DigitalCode="184",FullNameOfCHS="库克群岛",FullNameOfENG="Cook Islands"},
            new NationCode{ChineseAbbr="哥斯达黎加",EnglishAbbr="COSTA RIC",TwoCharCode="AC",ThreeCharCode="RCR",DigitalCode="188",FullNameOfCHS="哥斯达黎加共和国",FullNameOfENG="Republic of CostaRica"},
            new NationCode{ChineseAbbr="科特迪瓦",EnglishAbbr="COTE D'IVOIRE",TwoCharCode="CI",ThreeCharCode="CIV",DigitalCode="384",FullNameOfCHS="科特迪瓦共和国",FullNameOfENG="Republic of Coted'Ivire"},
            new NationCode{ChineseAbbr="克罗地亚",EnglishAbbr="CROATIA",TwoCharCode="HR",ThreeCharCode="HRV",DigitalCode="191",FullNameOfCHS="克罗地亚共和国",FullNameOfENG="Republic of Croatia"},
            new NationCode{ChineseAbbr="古巴",EnglishAbbr="CUBA",TwoCharCode="CU",ThreeCharCode="CUB",DigitalCode="192",FullNameOfCHS="古巴共和国",FullNameOfENG="Republic of Cuba"},
            new NationCode{ChineseAbbr="塞浦路斯",EnglishAbbr="CYPRUS",TwoCharCode="CY",ThreeCharCode="CYP",DigitalCode="196",FullNameOfCHS="塞浦路斯共和国",FullNameOfENG="Republic of Cyprus"},
            new NationCode{ChineseAbbr="捷克",EnglishAbbr="CZECH REPOUBLIC",TwoCharCode="CZ",ThreeCharCode="CZE",DigitalCode="203",FullNameOfCHS="捷克共和国",FullNameOfENG="Czech Republic"},
            new NationCode{ChineseAbbr="丹麦",EnglishAbbr="DENMARK",TwoCharCode="DK",ThreeCharCode="DNK",DigitalCode="208",FullNameOfCHS="丹麦王国",FullNameOfENG="Kingdom of Denmark"},
            new NationCode{ChineseAbbr="吉布提",EnglishAbbr="DJIBOUTI",TwoCharCode="DJ",ThreeCharCode="DJI",DigitalCode="262",FullNameOfCHS="吉布提共和国",FullNameOfENG="Republic of Djibouti"},
            new NationCode{ChineseAbbr="多米尼克",EnglishAbbr="DOMINICA",TwoCharCode="DM",ThreeCharCode="DMA",DigitalCode="212",FullNameOfCHS="多米尼克联邦",FullNameOfENG="Commonwealth ofDominica"},
            new NationCode{ChineseAbbr="多米尼加共和国",EnglishAbbr="DOMINICAN REPUBLIC",TwoCharCode="DO",ThreeCharCode="DOM",DigitalCode="214",FullNameOfCHS="多米尼加共和国",FullNameOfENG="Dominican Republic"},
            new NationCode{ChineseAbbr="东帝汶",EnglishAbbr="EAST TIMOR",TwoCharCode="TP",ThreeCharCode="TMP",DigitalCode="626",FullNameOfCHS="东帝汶",FullNameOfENG="East Timor"},
            new NationCode{ChineseAbbr="厄瓜多尔",EnglishAbbr="ECUADOR",TwoCharCode="EC",ThreeCharCode="ECU",DigitalCode="218",FullNameOfCHS="厄瓜多尔共和国",FullNameOfENG="Republic of Ecuador"},
            new NationCode{ChineseAbbr="埃及",EnglishAbbr="EGYPT",TwoCharCode="EG",ThreeCharCode="EGY",DigitalCode="818",FullNameOfCHS="阿拉伯埃及共和国",FullNameOfENG="Arab Republic ofEgypt"},
            new NationCode{ChineseAbbr="萨尔瓦多",EnglishAbbr="EL SALVADOR",TwoCharCode="SV",ThreeCharCode="SLV",DigitalCode="222",FullNameOfCHS="萨尔瓦多共和国",FullNameOfENG="Republic of ElSalvador"},
            new NationCode{ChineseAbbr="赤道几内亚",EnglishAbbr="EQUATORIAL GUINEA",TwoCharCode="GQ",ThreeCharCode="GNQ",DigitalCode="226",FullNameOfCHS="赤道几内亚共和国",FullNameOfENG="Republic ofEquatorial Guinea"},
            new NationCode{ChineseAbbr="厄立特里亚",EnglishAbbr="ERITREA",TwoCharCode="ER",ThreeCharCode="ERI",DigitalCode="232",FullNameOfCHS="厄立特里亚国",FullNameOfENG="State of Eritrea"},
            new NationCode{ChineseAbbr="爱沙尼亚",EnglishAbbr="ESTONIA",TwoCharCode="EE",ThreeCharCode="EST",DigitalCode="233",FullNameOfCHS="爱沙尼亚共和国",FullNameOfENG="Republic of Estonia"},
            new NationCode{ChineseAbbr="埃塞俄比亚",EnglishAbbr="ETHIOPIA",TwoCharCode="ET",ThreeCharCode="ETH",DigitalCode="231",FullNameOfCHS="埃塞俄比亚",FullNameOfENG="Ethiopia"},
            new NationCode{ChineseAbbr="福克兰群岛(马尔维纳斯)",EnglishAbbr="FALKLAND ISLANDS(MALVINAS)",TwoCharCode="FK",ThreeCharCode="FLK",DigitalCode="238",FullNameOfCHS="福克兰群岛(马尔维纳斯)",FullNameOfENG="FalklandIslands(Malvinas)"},
            new NationCode{ChineseAbbr="法罗群岛",EnglishAbbr="FAROE ISLANDS",TwoCharCode="FO",ThreeCharCode="FRO",DigitalCode="234",FullNameOfCHS="法罗群岛",FullNameOfENG="Faroe Islands"},
            new NationCode{ChineseAbbr="斐济",EnglishAbbr="FIJI",TwoCharCode="FJ",ThreeCharCode="FJI",DigitalCode="242",FullNameOfCHS="斐济共和国",FullNameOfENG="Republic of Fiji"},
            new NationCode{ChineseAbbr="芬兰",EnglishAbbr="FINLAND",TwoCharCode="FI",ThreeCharCode="FIN",DigitalCode="246",FullNameOfCHS="芬兰共和国",FullNameOfENG="Republic of Finland"},
            new NationCode{ChineseAbbr="法国",EnglishAbbr="FRANCE",TwoCharCode="FR",ThreeCharCode="FRA",DigitalCode="250",FullNameOfCHS="法兰西共和国",FullNameOfENG="French Republic"},
            new NationCode{ChineseAbbr="法属圭亚那",EnglishAbbr="FRENCH GUIANA",TwoCharCode="GF",ThreeCharCode="GUF",DigitalCode="254",FullNameOfCHS="法属圭亚那",FullNameOfENG="French Guiana"},
            new NationCode{ChineseAbbr="法属波利尼西亚",EnglishAbbr="FRENCH POLYNESIA",TwoCharCode="PF",ThreeCharCode="PYF",DigitalCode="258",FullNameOfCHS="法属波利尼西亚",FullNameOfENG="French Polynesia"},
            new NationCode{ChineseAbbr="法属南部领土",EnglishAbbr="FRENCH SOUTHERNTERRITO-RIES",TwoCharCode="TF",ThreeCharCode="ATF",DigitalCode="260",FullNameOfCHS="法属南部领土",FullNameOfENG="French SouthernTerritories"},
            new NationCode{ChineseAbbr="加蓬",EnglishAbbr="GABON",TwoCharCode="GA",ThreeCharCode="GAB",DigitalCode="266",FullNameOfCHS="加蓬共和国",FullNameOfENG="Gabonese Republic"},
            new NationCode{ChineseAbbr="冈比亚",EnglishAbbr="Gambia",TwoCharCode="GM",ThreeCharCode="GMB",DigitalCode="270",FullNameOfCHS="冈比亚共和国",FullNameOfENG="Republic of Gambia"},
            new NationCode{ChineseAbbr="格鲁吉亚",EnglishAbbr="GEORGIA",TwoCharCode="GE",ThreeCharCode="GEO",DigitalCode="268",FullNameOfCHS="格鲁吉亚共和国",FullNameOfENG="Republic of Georgia"},
            new NationCode{ChineseAbbr="德国",EnglishAbbr="GERMANY",TwoCharCode="DE",ThreeCharCode="DEU",DigitalCode="276",FullNameOfCHS="德意志联邦共和国",FullNameOfENG="Federal Republicof Germany"},
            new NationCode{ChineseAbbr="加纳",EnglishAbbr="GHANA",TwoCharCode="GH",ThreeCharCode="GHA",DigitalCode="288",FullNameOfCHS="加纳共和国",FullNameOfENG="Republic of Ghana"},
            new NationCode{ChineseAbbr="直布罗陀",EnglishAbbr="GIBRALTAR",TwoCharCode="GI",ThreeCharCode="GIB",DigitalCode="292",FullNameOfCHS="直布罗陀",FullNameOfENG="Gibraltar"},
            new NationCode{ChineseAbbr="希腊",EnglishAbbr="GREECE",TwoCharCode="GR",ThreeCharCode="GRC",DigitalCode="300",FullNameOfCHS="希腊共和国",FullNameOfENG="Hellenic Republic"},
            new NationCode{ChineseAbbr="格陵兰",EnglishAbbr="GREENLAND",TwoCharCode="GL",ThreeCharCode="GRL",DigitalCode="304",FullNameOfCHS="格陵兰",FullNameOfENG="Greenland"},
            new NationCode{ChineseAbbr="格林纳达",EnglishAbbr="GRENADA",TwoCharCode="GD",ThreeCharCode="GRD",DigitalCode="308",FullNameOfCHS="格林纳达",FullNameOfENG="Grenada"},
            new NationCode{ChineseAbbr="瓜德罗普",EnglishAbbr="GUADELOUPE",TwoCharCode="GP",ThreeCharCode="GLP",DigitalCode="312",FullNameOfCHS="瓜德罗普",FullNameOfENG="Guadeloupe"},
            new NationCode{ChineseAbbr="关岛",EnglishAbbr="GUAM",TwoCharCode="GU",ThreeCharCode="GUM",DigitalCode="316",FullNameOfCHS="关岛",FullNameOfENG="Guam"},
            new NationCode{ChineseAbbr="危地马拉",EnglishAbbr="GUATEMALA",TwoCharCode="GT",ThreeCharCode="GTM",DigitalCode="320",FullNameOfCHS="危地马拉共和国",FullNameOfENG="Republic ofGuatemala"},
            new NationCode{ChineseAbbr="几内亚",EnglishAbbr="GUINEA",TwoCharCode="GN",ThreeCharCode="GIN",DigitalCode="324",FullNameOfCHS="几内亚共和国",FullNameOfENG="Republic of Guinea"},
            new NationCode{ChineseAbbr="几内亚比绍",EnglishAbbr="GUINE-BISSAU",TwoCharCode="GW",ThreeCharCode="GNB",DigitalCode="624",FullNameOfCHS="几内亚比绍共和国",FullNameOfENG="Republic ofGuine-bissau"},
            new NationCode{ChineseAbbr="圭亚那",EnglishAbbr="GUYANA",TwoCharCode="GY",ThreeCharCode="GUY",DigitalCode="328",FullNameOfCHS="圭亚那合作共和国",FullNameOfENG="CooperativeRepublic of Guyana"},
            new NationCode{ChineseAbbr="海地",EnglishAbbr="HAITI",TwoCharCode="HT",ThreeCharCode="HTI",DigitalCode="332",FullNameOfCHS="海地共和国",FullNameOfENG="Republic of Haiti"},
            new NationCode{ChineseAbbr="赫德岛和麦克唐纳岛",EnglishAbbr="HEARD ISLANDS AND MCDONALD ISLANDS",TwoCharCode="HM",ThreeCharCode="HMD",DigitalCode="334",FullNameOfCHS="赫德岛和麦克唐纳岛",FullNameOfENG="Heard islandsand Mc Donald Islands"},
            new NationCode{ChineseAbbr="洪都拉斯",EnglishAbbr="HONDURAS",TwoCharCode="HN",ThreeCharCode="HND",DigitalCode="340",FullNameOfCHS="洪都拉斯共和国",FullNameOfENG="Republic ofhonduras"},
            new NationCode{ChineseAbbr="匈牙利",EnglishAbbr="HUNGARY",TwoCharCode="HU",ThreeCharCode="HUN",DigitalCode="348",FullNameOfCHS="匈牙利共和国",FullNameOfENG="Republic of Hungary"},
            new NationCode{ChineseAbbr="冰岛",EnglishAbbr="ICELAND",TwoCharCode="IS",ThreeCharCode="ISL",DigitalCode="352",FullNameOfCHS="冰岛共和国",FullNameOfENG="Republic of Iceland"},
            new NationCode{ChineseAbbr="印度",EnglishAbbr="INDIA",TwoCharCode="IN",ThreeCharCode="IND",DigitalCode="356",FullNameOfCHS="印度共和国",FullNameOfENG="Republic of India"},
            new NationCode{ChineseAbbr="印度尼西亚",EnglishAbbr="INDONESIA",TwoCharCode="ID",ThreeCharCode="IDN",DigitalCode="360",FullNameOfCHS="印度尼西亚共和国",FullNameOfENG="Republic ofIndonesia"},
            new NationCode{ChineseAbbr="伊朗",EnglishAbbr="IRAN",TwoCharCode="IR",ThreeCharCode="IRN",DigitalCode="364",FullNameOfCHS="伊朗伊斯兰共和国",FullNameOfENG="Islamic Rupublicof Iran"},
            new NationCode{ChineseAbbr="伊拉克",EnglishAbbr="IRAQ",TwoCharCode="IQ",ThreeCharCode="IRQ",DigitalCode="368",FullNameOfCHS="伊拉克共和国",FullNameOfENG="Republic of Iraq"},
            new NationCode{ChineseAbbr="爱尔兰",EnglishAbbr="IRELAND",TwoCharCode="IE",ThreeCharCode="IRL",DigitalCode="372",FullNameOfCHS="爱尔兰",FullNameOfENG="Ireland"},
            new NationCode{ChineseAbbr="以色列",EnglishAbbr="ISRAEL",TwoCharCode="IL",ThreeCharCode="ISR",DigitalCode="376",FullNameOfCHS="以色列国",FullNameOfENG="State of Israel"},
            new NationCode{ChineseAbbr="意大利",EnglishAbbr="ITALY",TwoCharCode="IT",ThreeCharCode="ITA",DigitalCode="380",FullNameOfCHS="意大利共和国",FullNameOfENG="Republic of Italy"},
            new NationCode{ChineseAbbr="牙买加",EnglishAbbr="JAMAICA",TwoCharCode="JM",ThreeCharCode="JAM",DigitalCode="388",FullNameOfCHS="牙买加",FullNameOfENG="Jamaica"},
            new NationCode{ChineseAbbr="日本",EnglishAbbr="JAPAN",TwoCharCode="JP",ThreeCharCode="JPN",DigitalCode="392",FullNameOfCHS="日本国",FullNameOfENG="Japan"},
            new NationCode{ChineseAbbr="约旦",EnglishAbbr="JORDAN",TwoCharCode="JO",ThreeCharCode="JOR",DigitalCode="400",FullNameOfCHS="约旦哈希姆王国",FullNameOfENG="Hashemite Kingdomof Jordan"},
            new NationCode{ChineseAbbr="哈萨克斯坦",EnglishAbbr="KAZAKHSTAN",TwoCharCode="KZ",ThreeCharCode="KAZ",DigitalCode="398",FullNameOfCHS="哈萨克斯坦共和国",FullNameOfENG="Republic ofKazakhstan"},
            new NationCode{ChineseAbbr="肯尼亚",EnglishAbbr="KENYA",TwoCharCode="KE",ThreeCharCode="KEN",DigitalCode="404",FullNameOfCHS="肯尼亚共和国",FullNameOfENG="Republic of Kenya"},
            new NationCode{ChineseAbbr="基里巴斯",EnglishAbbr="KIRIBATI",TwoCharCode="KI",ThreeCharCode="KIR",DigitalCode="296",FullNameOfCHS="基里巴斯共和国",FullNameOfENG="Republic ofKiribati"},
            new NationCode{ChineseAbbr="朝鲜",EnglishAbbr="KOREA,DEMOCRATICPEOPLE'S REPUBLIC OF",TwoCharCode="KP",ThreeCharCode="PRK",DigitalCode="408",FullNameOfCHS="朝鲜民主主义人民共和国",FullNameOfENG="DemocraticPeople's Republic of Ko-rea"},
            new NationCode{ChineseAbbr="韩国",EnglishAbbr="KOREA,REPUBLIC OF",TwoCharCode="KR",ThreeCharCode="KOR",DigitalCode="410",FullNameOfCHS="大韩民国",FullNameOfENG="Republic of Korea"},
            new NationCode{ChineseAbbr="科威特",EnglishAbbr="KUWAIT",TwoCharCode="KW",ThreeCharCode="KWT",DigitalCode="414",FullNameOfCHS="科威特国",FullNameOfENG="State of Kuwait"},
            new NationCode{ChineseAbbr="吉尔吉斯斯坦",EnglishAbbr="KYRGYZSTAN",TwoCharCode="KG",ThreeCharCode="KGZ",DigitalCode="417",FullNameOfCHS="吉尔吉斯共和国",FullNameOfENG="Kyrgyz Republic"},
            new NationCode{ChineseAbbr="老挝",EnglishAbbr="LAOS",TwoCharCode="LA",ThreeCharCode="LAO",DigitalCode="418",FullNameOfCHS="老挝人民民主共和国",FullNameOfENG="Lao People'sDemocratic Republic"},
            new NationCode{ChineseAbbr="拉脱维亚",EnglishAbbr="LATVIA",TwoCharCode="LV",ThreeCharCode="LVA",DigitalCode="428",FullNameOfCHS="拉脱维亚共和国",FullNameOfENG="Republic of Latvia"},
            new NationCode{ChineseAbbr="黎巴嫩",EnglishAbbr="LEBANON",TwoCharCode="LB",ThreeCharCode="LBN",DigitalCode="422",FullNameOfCHS="黎巴嫩共和国",FullNameOfENG="Republic of Lebanon"},
            new NationCode{ChineseAbbr="莱索托",EnglishAbbr="LESOTHO",TwoCharCode="LS",ThreeCharCode="LSO",DigitalCode="426",FullNameOfCHS="莱索托王国",FullNameOfENG="Kingdom of Lesoto"},
            new NationCode{ChineseAbbr="利比里亚",EnglishAbbr="LIBERIA",TwoCharCode="LR",ThreeCharCode="LBR",DigitalCode="430",FullNameOfCHS="利比里亚共和国",FullNameOfENG="Republic of Liberia"},
            new NationCode{ChineseAbbr="利比亚",EnglishAbbr="LIBYA",TwoCharCode="LY",ThreeCharCode="LBY",DigitalCode="434",FullNameOfCHS="大阿拉伯利比亚人民社会主义民众国Great",FullNameOfENG="Socialist People's Libyan Arab jamahiriya"},
            new NationCode{ChineseAbbr="列支敦士登",EnglishAbbr="LIECHTENSTEIN",TwoCharCode="LI",ThreeCharCode="LIE",DigitalCode="438",FullNameOfCHS="列支敦士登公国",FullNameOfENG="Principality ofLiechtenstein"},
            new NationCode{ChineseAbbr="立陶宛",EnglishAbbr="LITHUANIA",TwoCharCode="LT",ThreeCharCode="LTU",DigitalCode="440",FullNameOfCHS="立陶宛共和国",FullNameOfENG="Republic of Lithuania"},
            new NationCode{ChineseAbbr="卢森堡",EnglishAbbr="LUXEMBOURG",TwoCharCode="LU",ThreeCharCode="LUX",DigitalCode="442",FullNameOfCHS="卢森堡大公国",FullNameOfENG="Grand Duchy ofLuxembourg"},
            new NationCode{ChineseAbbr="前南马其顿",EnglishAbbr="MACEDONIA, THE FORMERYUGOSLAV REPUBLIC OF",TwoCharCode="MK",ThreeCharCode="MKD",DigitalCode="807",FullNameOfCHS="前南斯拉夫马其顿共和国",FullNameOfENG="The FormerYugoslav Republic of Macedonia"},
            new NationCode{ChineseAbbr="马达加斯加",EnglishAbbr="MADAGASCAR",TwoCharCode="MG",ThreeCharCode="MDG",DigitalCode="450",FullNameOfCHS="马达加斯加共和国",FullNameOfENG="Republic ofMadagascar"},
            new NationCode{ChineseAbbr="马拉维",EnglishAbbr="MALAWI",TwoCharCode="MW",ThreeCharCode="MWI",DigitalCode="454",FullNameOfCHS="马拉维共和国",FullNameOfENG="Republic of Malawi"},
            new NationCode{ChineseAbbr="马来西亚",EnglishAbbr="MALAYSIA",TwoCharCode="MY",ThreeCharCode="MYS",DigitalCode="458",FullNameOfCHS="马来西亚",FullNameOfENG="Malaysia"},
            new NationCode{ChineseAbbr="马尔代夫",EnglishAbbr="MALDIVES",TwoCharCode="MV",ThreeCharCode="MDV",DigitalCode="462",FullNameOfCHS="马尔代夫共和国",FullNameOfENG="Republic ofmaldives"},
            new NationCode{ChineseAbbr="马里",EnglishAbbr="MALI",TwoCharCode="ML",ThreeCharCode="MLI",DigitalCode="466",FullNameOfCHS="马里共和国",FullNameOfENG="Republic of Mali"},
            new NationCode{ChineseAbbr="马耳他",EnglishAbbr="MALTA",TwoCharCode="MT",ThreeCharCode="MLT",DigitalCode="470",FullNameOfCHS="马耳他共和国",FullNameOfENG="Republic of Malta"},
            new NationCode{ChineseAbbr="马绍尔群岛",EnglishAbbr="MARSHALL ISLANDS",TwoCharCode="MH",ThreeCharCode="MHL",DigitalCode="584",FullNameOfCHS="马绍尔群岛共和国",FullNameOfENG="Republic of themarshall Islands"},
            new NationCode{ChineseAbbr="马提尼克",EnglishAbbr="MARTINIQUE",TwoCharCode="MQ",ThreeCharCode="MTQ",DigitalCode="474",FullNameOfCHS="马提尼克",FullNameOfENG="Martinique"},
            new NationCode{ChineseAbbr="毛里塔尼亚",EnglishAbbr="MAURITANIA",TwoCharCode="MR",ThreeCharCode="MRT",DigitalCode="478",FullNameOfCHS="毛里求斯共和国",FullNameOfENG="Republic ofMauritius"},
            new NationCode{ChineseAbbr="毛里求斯",EnglishAbbr="MAURITIUS",TwoCharCode="MU",ThreeCharCode="MUS",DigitalCode="480",FullNameOfCHS="毛里求斯共和国",FullNameOfENG="Republic ofMauritius"},
            new NationCode{ChineseAbbr="马约特",EnglishAbbr="MAYOTTE",TwoCharCode="YT",ThreeCharCode="MYT",DigitalCode="175",FullNameOfCHS="马约特",FullNameOfENG="Mayotte"},
            new NationCode{ChineseAbbr="墨西哥",EnglishAbbr="MEXICO",TwoCharCode="MX",ThreeCharCode="MEX",DigitalCode="484",FullNameOfCHS="墨西哥合众国",FullNameOfENG="United States ofMexico"},
            new NationCode{ChineseAbbr="密克罗尼西亚联邦",EnglishAbbr="MICRONESIA, FEDERATEDSTATES OF",TwoCharCode="FM",ThreeCharCode="FSM",DigitalCode="583",FullNameOfCHS="密克罗尼西亚联邦",FullNameOfENG="Federated Statesof Micronesia"},
            new NationCode{ChineseAbbr="摩尔多瓦",EnglishAbbr="MOLDOVA",TwoCharCode="MD",ThreeCharCode="MDA",DigitalCode="498",FullNameOfCHS="摩尔多瓦共和国",FullNameOfENG="Republic of Moldova"},
            new NationCode{ChineseAbbr="摩纳哥",EnglishAbbr="MONACO",TwoCharCode="MC",ThreeCharCode="MCO",DigitalCode="492",FullNameOfCHS="摩纳哥公国",FullNameOfENG="Principality of Monaco"},
            new NationCode{ChineseAbbr="蒙古",EnglishAbbr="MONGOLIA",TwoCharCode="MN",ThreeCharCode="MNG",DigitalCode="496",FullNameOfCHS="蒙古国",FullNameOfENG="Mongolia"},
            new NationCode{ChineseAbbr="蒙特塞拉特",EnglishAbbr="MONTSERRAT",TwoCharCode="MS",ThreeCharCode="MSR",DigitalCode="500",FullNameOfCHS="蒙特塞拉特",FullNameOfENG="Montserrat"},
            new NationCode{ChineseAbbr="摩洛哥",EnglishAbbr="MOROCCO",TwoCharCode="MA",ThreeCharCode="MAR",DigitalCode="504",FullNameOfCHS="摩洛哥王国",FullNameOfENG="Kingdom of Morocco"},
            new NationCode{ChineseAbbr="莫桑比克",EnglishAbbr="MOZAMBIQUE",TwoCharCode="MZ",ThreeCharCode="MOZ",DigitalCode="508",FullNameOfCHS="莫桑比克共和国",FullNameOfENG="Republic ofMozambique"},
            new NationCode{ChineseAbbr="缅甸",EnglishAbbr="MYANMAR",TwoCharCode="MM",ThreeCharCode="MMR",DigitalCode="104",FullNameOfCHS="缅甸联邦",FullNameOfENG="Union of Myanmar"},
            new NationCode{ChineseAbbr="纳米比亚",EnglishAbbr="NAMIBIA",TwoCharCode="NA",ThreeCharCode="NAM",DigitalCode="516",FullNameOfCHS="纳米比亚共和国",FullNameOfENG="Republic of Namibia"},
            new NationCode{ChineseAbbr="瑙鲁",EnglishAbbr="NAURU",TwoCharCode="NR",ThreeCharCode="NRU",DigitalCode="520",FullNameOfCHS="瑙鲁共和国",FullNameOfENG="Republic of Nauru"},
            new NationCode{ChineseAbbr="尼泊尔",EnglishAbbr="NEPAL",TwoCharCode="NP",ThreeCharCode="NPL",DigitalCode="524",FullNameOfCHS="尼泊尔王国",FullNameOfENG="Kingdom of Nepal"},
            new NationCode{ChineseAbbr="荷兰",EnglishAbbr="NETHERLANDS",TwoCharCode="NL",ThreeCharCode="NLD",DigitalCode="528",FullNameOfCHS="荷兰王国",FullNameOfENG="Kingdom of theNetherlands"},
            new NationCode{ChineseAbbr="荷属安的列斯",EnglishAbbr="NETHERLANDS ANTILLES",TwoCharCode="AN",ThreeCharCode="ANT",DigitalCode="530",FullNameOfCHS="荷属安的列斯",FullNameOfENG="Netherlands Antilles"},
            new NationCode{ChineseAbbr="新喀里多尼亚",EnglishAbbr="NEW CALEDONIA",TwoCharCode="NC",ThreeCharCode="NCL",DigitalCode="540",FullNameOfCHS="新喀里多尼亚",FullNameOfENG="New Caledonia"},
            new NationCode{ChineseAbbr="新西兰",EnglishAbbr="NEW ZEALAND",TwoCharCode="NZ",ThreeCharCode="NZL",DigitalCode="554",FullNameOfCHS="新西兰",FullNameOfENG="New Zealand"},
            new NationCode{ChineseAbbr="尼加拉瓜",EnglishAbbr="NICARAGUA",TwoCharCode="NI",ThreeCharCode="NIC",DigitalCode="558",FullNameOfCHS="尼加拉瓜共和国",FullNameOfENG="Republic ofNicaragua"},
            new NationCode{ChineseAbbr="尼日尔",EnglishAbbr="NIGER",TwoCharCode="NE",ThreeCharCode="NER",DigitalCode="562",FullNameOfCHS="尼日尔共和国",FullNameOfENG="Republic of Niger"},
            new NationCode{ChineseAbbr="尼日利亚",EnglishAbbr="NIGERIA",TwoCharCode="NG",ThreeCharCode="NGA",DigitalCode="566",FullNameOfCHS="尼日利亚联邦共和国",FullNameOfENG="FederalRepublic of Nigeria"},
            new NationCode{ChineseAbbr="纽埃",EnglishAbbr="NIUE",TwoCharCode="NU",ThreeCharCode="NIU",DigitalCode="570",FullNameOfCHS="纽埃",FullNameOfENG="Niue"},
            new NationCode{ChineseAbbr="诺福克岛",EnglishAbbr="NORFOLK ISLAND",TwoCharCode="NF",ThreeCharCode="NFK",DigitalCode="574",FullNameOfCHS="诺福克岛",FullNameOfENG="Norfolk Island"},
            new NationCode{ChineseAbbr="北马里亚纳",EnglishAbbr="NORTHERN MARIANAS",TwoCharCode="MP",ThreeCharCode="MNP",DigitalCode="580",FullNameOfCHS="北马里亚纳自由联邦",FullNameOfENG="Commonwealth ofthe Northern Marianas"},
            new NationCode{ChineseAbbr="挪威",EnglishAbbr="NORWAY",TwoCharCode="NO",ThreeCharCode="NOR",DigitalCode="578",FullNameOfCHS="挪威王国",FullNameOfENG="Kingdom of Norway"},
            new NationCode{ChineseAbbr="阿曼",EnglishAbbr="OMAN",TwoCharCode="OM",ThreeCharCode="OMN",DigitalCode="512",FullNameOfCHS="阿曼苏丹国",FullNameOfENG="Sultanate of Oman"},
            new NationCode{ChineseAbbr="巴基斯坦",EnglishAbbr="PAKISTAN",TwoCharCode="PK",ThreeCharCode="PAK",DigitalCode="586",FullNameOfCHS="巴基斯坦伊斯兰共和国",FullNameOfENG="IslamicRepublic of Pakistan"},
            new NationCode{ChineseAbbr="帕劳",EnglishAbbr="PALAU",TwoCharCode="PW",ThreeCharCode="PLW",DigitalCode="585",FullNameOfCHS="帕劳共和国",FullNameOfENG="Republic of Palau"},
            new NationCode{ChineseAbbr="巴勒斯坦",EnglishAbbr="PALESTINE",TwoCharCode="PS",ThreeCharCode="PST",DigitalCode="374",FullNameOfCHS="巴勒斯坦国",FullNameOfENG="State of Palestine"},
            new NationCode{ChineseAbbr="巴拿马",EnglishAbbr="PANAMA",TwoCharCode="PA",ThreeCharCode="PAN",DigitalCode="591",FullNameOfCHS="巴拿马共和国",FullNameOfENG="Republic of Panama"},
            new NationCode{ChineseAbbr="巴布亚新几内亚",EnglishAbbr="PAPUA NEW GUINEA",TwoCharCode="PG",ThreeCharCode="PNG",DigitalCode="598",FullNameOfCHS="巴布亚新几内亚独立国",FullNameOfENG="IndependentState of Papua New Guinea"},
            new NationCode{ChineseAbbr="巴拉圭",EnglishAbbr="PARAGUAY",TwoCharCode="PY",ThreeCharCode="PRY",DigitalCode="600",FullNameOfCHS="巴拉圭共和国",FullNameOfENG="Republic of Paraguay"},
            new NationCode{ChineseAbbr="秘鲁",EnglishAbbr="PERU",TwoCharCode="PE",ThreeCharCode="PER",DigitalCode="604",FullNameOfCHS="秘鲁共和国",FullNameOfENG="Republic of Peru"},
            new NationCode{ChineseAbbr="菲律宾",EnglishAbbr="PHILIPPINES",TwoCharCode="PH",ThreeCharCode="PHL",DigitalCode="608",FullNameOfCHS="菲律宾共和国",FullNameOfENG="Republic of thePhilippines"},
            new NationCode{ChineseAbbr="皮特凯恩群岛",EnglishAbbr="PITCAIRN ISLANDSGROUP",TwoCharCode="PN",ThreeCharCode="PCN",DigitalCode="612",FullNameOfCHS="皮竺凯恩群岛",FullNameOfENG="Pitcairn IslandsGroup"},
            new NationCode{ChineseAbbr="波兰",EnglishAbbr="POLAND",TwoCharCode="PL",ThreeCharCode="POL",DigitalCode="616",FullNameOfCHS="波兰共和国",FullNameOfENG="Republic of Poland"},
            new NationCode{ChineseAbbr="葡萄牙",EnglishAbbr="PORTUGAL",TwoCharCode="PT",ThreeCharCode="PRT",DigitalCode="620",FullNameOfCHS="葡萄牙共和国",FullNameOfENG="Pirtuguese Republic"},
            new NationCode{ChineseAbbr="波多黎各",EnglishAbbr="PUERTO RICO",TwoCharCode="PR",ThreeCharCode="PRI",DigitalCode="630",FullNameOfCHS="波多黎各自由联邦",FullNameOfENG="Commonwealth ofPuerto Rico"},
            new NationCode{ChineseAbbr="卡塔尔",EnglishAbbr="QATAR",TwoCharCode="QA",ThreeCharCode="QAT",DigitalCode="634",FullNameOfCHS="卡塔尔国",FullNameOfENG="State of Qatar"},
            new NationCode{ChineseAbbr="留尼汪",EnglishAbbr="REUNION",TwoCharCode="RE",ThreeCharCode="REU",DigitalCode="638",FullNameOfCHS="留尼汪",FullNameOfENG="Reunion"},
            new NationCode{ChineseAbbr="罗马尼亚",EnglishAbbr="ROMANIA",TwoCharCode="RO",ThreeCharCode="ROM",DigitalCode="642",FullNameOfCHS="罗马尼亚",FullNameOfENG="Romania"},
            new NationCode{ChineseAbbr="俄罗斯联邦",EnglishAbbr="RUSSIAN FEDERATION",TwoCharCode="RU",ThreeCharCode="RUS",DigitalCode="643",FullNameOfCHS="俄罗斯联邦",FullNameOfENG="Russian Federation"},
            new NationCode{ChineseAbbr="卢旺达",EnglishAbbr="RWANDA",TwoCharCode="RW",ThreeCharCode="RWA",DigitalCode="646",FullNameOfCHS="卢旺达共和国",FullNameOfENG="Republic of Rwanda"},
            new NationCode{ChineseAbbr="圣赫勒拿",EnglishAbbr="SAINT HELENA",TwoCharCode="Sh",ThreeCharCode="SHN",DigitalCode="654",FullNameOfCHS="对赫勒拿",FullNameOfENG="Saint Helena"},
            new NationCode{ChineseAbbr="圣基茨和尼维斯",EnglishAbbr="SAINT KITTS AND NEVIS",TwoCharCode="KN",ThreeCharCode="KNA",DigitalCode="659",FullNameOfCHS="圣革茨和尼维斯联邦",FullNameOfENG="Federation ofSaint Kitts and nevis"},
            new NationCode{ChineseAbbr="圣卢西亚",EnglishAbbr="SAINT LUCIA",TwoCharCode="LC",ThreeCharCode="LCA",DigitalCode="662",FullNameOfCHS="圣卢西亚",FullNameOfENG="Saint Lucia"},
            new NationCode{ChineseAbbr="圣皮埃尔和密克隆",EnglishAbbr="SAINT PIERRE ANDMIQUELON",TwoCharCode="PM",ThreeCharCode="SPM",DigitalCode="666",FullNameOfCHS="圣皮埃尔和密克隆",FullNameOfENG="Saint Pierre andMiquelon"},
            new NationCode{ChineseAbbr="圣文森特和格林纳丁斯",EnglishAbbr="SAINT VINCENT AND THEGRENADINES",TwoCharCode="VC",ThreeCharCode="VCT",DigitalCode="670",FullNameOfCHS="圣文森特和格林纳丁斯",FullNameOfENG="Saint Vincentand the Grenadines"},
            new NationCode{ChineseAbbr="萨摩亚",EnglishAbbr="SAMOA",TwoCharCode="WS",ThreeCharCode="WSM",DigitalCode="882",FullNameOfCHS="萨摩亚独立国",FullNameOfENG="Independent State ofSamoa"},
            new NationCode{ChineseAbbr="圣马力诺",EnglishAbbr="SAN MARION",TwoCharCode="SM",ThreeCharCode="SMR",DigitalCode="674",FullNameOfCHS="圣马力诺共和国",FullNameOfENG="Republic of SanMarino"},
            new NationCode{ChineseAbbr="圣多美和普林西 比",EnglishAbbr="SAO TOME AND PRINCIPE",TwoCharCode="St",ThreeCharCode="STp",DigitalCode="678",FullNameOfCHS="圣多美和普林西比民主共和国",FullNameOfENG="Democratic Republic of Sao Tomeand Principe"},
            new NationCode{ChineseAbbr="沙特阿拉伯",EnglishAbbr="SAUDI ARABIA",TwoCharCode="SA",ThreeCharCode="SAU",DigitalCode="682",FullNameOfCHS="沙特阿拉伯王国",FullNameOfENG="Kingdom of SaudiArabia"},
            new NationCode{ChineseAbbr="塞内加尔",EnglishAbbr="SENEGAL",TwoCharCode="SN",ThreeCharCode="SEN",DigitalCode="686",FullNameOfCHS="塞内加尔共和国",FullNameOfENG="Republic of Senegal"},
            new NationCode{ChineseAbbr="塞舌尔",EnglishAbbr="SEYCHELLS",TwoCharCode="SC",ThreeCharCode="SYC",DigitalCode="690",FullNameOfCHS="塞舌尔共和国",FullNameOfENG="Republic ofSeychelles"},
            new NationCode{ChineseAbbr="塞拉利昂",EnglishAbbr="SIERRA LEONE",TwoCharCode="SL",ThreeCharCode="SLE",DigitalCode="694",FullNameOfCHS="塞拉利昂共和国",FullNameOfENG="Republic of SierraLeone"},
            new NationCode{ChineseAbbr="新加坡",EnglishAbbr="SINGAPORE",TwoCharCode="SG",ThreeCharCode="SGP",DigitalCode="702",FullNameOfCHS="新加坡共和国",FullNameOfENG="Republic of Singapore"},
            new NationCode{ChineseAbbr="斯洛伐克",EnglishAbbr="SLOVAKIA",TwoCharCode="SK",ThreeCharCode="SVK",DigitalCode="703",FullNameOfCHS="斯洛伐克共和国",FullNameOfENG="Slovak Republic"},
            new NationCode{ChineseAbbr="斯洛文尼亚",EnglishAbbr="SLOVENIA",TwoCharCode="SI",ThreeCharCode="SVN",DigitalCode="705",FullNameOfCHS="斯洛文尼亚共和国",FullNameOfENG="Republic ofSlovenia"},
            new NationCode{ChineseAbbr="所罗门群岛",EnglishAbbr="SOLOMON ISLANDS",TwoCharCode="SB",ThreeCharCode="SLB",DigitalCode="090",FullNameOfCHS="年罗门群岛",FullNameOfENG="Solomon Islands"},
            new NationCode{ChineseAbbr="索马里",EnglishAbbr="SOMALIA",TwoCharCode="SO",ThreeCharCode="SOM",DigitalCode="706",FullNameOfCHS="索马里共和国",FullNameOfENG="Somali Republic"},
            new NationCode{ChineseAbbr="南非",EnglishAbbr="SOUTH AFRICA",TwoCharCode="ZA",ThreeCharCode="ZAF",DigitalCode="710",FullNameOfCHS="南非共和国",FullNameOfENG="Republic of SouthAfrica"},
            new NationCode{ChineseAbbr="南乔治亚岛和南桑德韦奇岛",EnglishAbbr="SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS",TwoCharCode="GS",ThreeCharCode="SGS",DigitalCode="239",FullNameOfCHS="南乔治亚岛和南桑德韦奇岛",FullNameOfENG="South Georgia and South Sandwich Islands"},
            new NationCode{ChineseAbbr="西班牙",EnglishAbbr="SPAIN",TwoCharCode="ES",ThreeCharCode="ESP",DigitalCode="724",FullNameOfCHS="西班牙",FullNameOfENG="Spain"},
            new NationCode{ChineseAbbr="斯里兰卡",EnglishAbbr="SRI LANKA",TwoCharCode="LK",ThreeCharCode="LKA",DigitalCode="144",FullNameOfCHS="斯里兰卡民主社会主义共和国",FullNameOfENG="Democratic Socialist Republic of Srilanka"},
            new NationCode{ChineseAbbr="苏丹",EnglishAbbr="SUDAN",TwoCharCode="SD",ThreeCharCode="SDN",DigitalCode="736",FullNameOfCHS="苏丹共和国",FullNameOfENG="Republic of the Sudan"},
            new NationCode{ChineseAbbr="苏里南",EnglishAbbr="SURINAME",TwoCharCode="SR",ThreeCharCode="SUR",DigitalCode="740",FullNameOfCHS="苏里南共和国",FullNameOfENG="Republic of Suriname"},
            new NationCode{ChineseAbbr="斯瓦尔巴群岛",EnglishAbbr="SVALBARD AND JANMAYEN ISLANDS",TwoCharCode="SJ",ThreeCharCode="SJM",DigitalCode="744",FullNameOfCHS="斯瓦尔巴群岛",FullNameOfENG="Svalbard and Janmayen islands"},
            new NationCode{ChineseAbbr="斯威士兰",EnglishAbbr="SWAZILAND",TwoCharCode="SZ",ThreeCharCode="SWZ",DigitalCode="748",FullNameOfCHS="斯威士兰王国",FullNameOfENG="Kingdom of Swaziland"},
            new NationCode{ChineseAbbr="瑞典",EnglishAbbr="SWEDEN",TwoCharCode="SE",ThreeCharCode="SWE",DigitalCode="752",FullNameOfCHS="瑞典王国",FullNameOfENG="Kingdom of Sweden"},
            new NationCode{ChineseAbbr="瑞士",EnglishAbbr="SWITZERLAND",TwoCharCode="CH",ThreeCharCode="CHE",DigitalCode="756",FullNameOfCHS="瑞士联邦",FullNameOfENG="Swiss Confederation"},
            new NationCode{ChineseAbbr="叙利亚",EnglishAbbr="SYRIA",TwoCharCode="SY",ThreeCharCode="SYR",DigitalCode="760",FullNameOfCHS="阿拉伯叙利亚共和国",FullNameOfENG="Syrian ArabRepublic"},
            new NationCode{ChineseAbbr="塔吉克斯坦",EnglishAbbr="TAJIKISTAN",TwoCharCode="TJ",ThreeCharCode="TJK",DigitalCode="762",FullNameOfCHS="塔吉克斯坦共和国",FullNameOfENG="Republic ofTajikistan"},
            new NationCode{ChineseAbbr="坦桑尼亚",EnglishAbbr="TANZANIA",TwoCharCode="TZ",ThreeCharCode="TZA",DigitalCode="834",FullNameOfCHS="坦桑尼亚联合共和国",FullNameOfENG="United Republicof Tanzania"},
            new NationCode{ChineseAbbr="泰国",EnglishAbbr="THAILAND",TwoCharCode="TH",ThreeCharCode="THA",DigitalCode="764",FullNameOfCHS="泰王国",FullNameOfENG="Kingdom of Thailand"},
            new NationCode{ChineseAbbr="多哥",EnglishAbbr="TOGO",TwoCharCode="TG",ThreeCharCode="TGO",DigitalCode="768",FullNameOfCHS="多哥共和国",FullNameOfENG="Republic of Tago"},
            new NationCode{ChineseAbbr="托克劳",EnglishAbbr="TOKELAU",TwoCharCode="TK",ThreeCharCode="TKL",DigitalCode="772",FullNameOfCHS="托克劳",FullNameOfENG="Tokelau"},
            new NationCode{ChineseAbbr="汤加",EnglishAbbr="TONGA",TwoCharCode="TO",ThreeCharCode="TON",DigitalCode="776",FullNameOfCHS="汤加王国",FullNameOfENG="Kingdom of Tonga"},
            new NationCode{ChineseAbbr="特立尼达和多巴哥",EnglishAbbr="TRINIDAD AND TOBAGO",TwoCharCode="TT",ThreeCharCode="TTO",DigitalCode="780",FullNameOfCHS="特立尼达和多巴哥共和国",FullNameOfENG="Republic ofTrinidad and Tobago"},
            new NationCode{ChineseAbbr="突尼斯",EnglishAbbr="TUNISIA",TwoCharCode="TN",ThreeCharCode="TUN",DigitalCode="788",FullNameOfCHS="突尼斯共和国",FullNameOfENG="Republic of Tunisia"},
            new NationCode{ChineseAbbr="土耳其",EnglishAbbr="TURKEY",TwoCharCode="TR",ThreeCharCode="TUR",DigitalCode="792",FullNameOfCHS="土耳其共和国",FullNameOfENG="Republic of Turkey"},
            new NationCode{ChineseAbbr="土库曼斯坦",EnglishAbbr="TURKMENISTAN",TwoCharCode="TM",ThreeCharCode="TKM",DigitalCode="795",FullNameOfCHS="土库曼斯坦",FullNameOfENG="Turkmenistan"},
            new NationCode{ChineseAbbr="特克斯科斯群岛",EnglishAbbr="TURKS AND CAICOS ISLANDS",TwoCharCode="TC",ThreeCharCode="TCA",DigitalCode="796",FullNameOfCHS="特克斯和凯科斯群岛",FullNameOfENG="Turks andCaicos Islands"},
            new NationCode{ChineseAbbr="图瓦卢",EnglishAbbr="TUVALU",TwoCharCode="TV",ThreeCharCode="TUV",DigitalCode="798",FullNameOfCHS="图瓦卢",FullNameOfENG="Tuvalu"},
            new NationCode{ChineseAbbr="乌干达",EnglishAbbr="UGANDA",TwoCharCode="UG",ThreeCharCode="UGA",DigitalCode="800",FullNameOfCHS="乌干达共和国",FullNameOfENG="Republic of Uganda"},
            new NationCode{ChineseAbbr="乌克兰",EnglishAbbr="UKRAINE",TwoCharCode="UA",ThreeCharCode="UKR",DigitalCode="804",FullNameOfCHS="乌克兰",FullNameOfENG="Ukraine"},
            new NationCode{ChineseAbbr="阿联酋",EnglishAbbr="UNITED ARAB EMIRATES",TwoCharCode="AE",ThreeCharCode="ARE",DigitalCode="784",FullNameOfCHS="拉伯联合酋长国",FullNameOfENG="United ArabEmirates"},
            new NationCode{ChineseAbbr="英国",EnglishAbbr="UNITED KINGDOM",TwoCharCode="GB",ThreeCharCode="GBR",DigitalCode="826",FullNameOfCHS="大不列颠及北爱尔兰联合王国",FullNameOfENG="UnitedKingdom of Great Britain and Northern ireland"},
            new NationCode{ChineseAbbr="美国",EnglishAbbr="UNITED STATES",TwoCharCode="US",ThreeCharCode="USA",DigitalCode="840",FullNameOfCHS="美利坚合众国",FullNameOfENG="United States ofAmerica"},
            new NationCode{ChineseAbbr="美国本土外小岛屿",EnglishAbbr="UNITED STATES MINOR OUTLYING ISLANDS",TwoCharCode="UM",ThreeCharCode="UMI",DigitalCode="581",FullNameOfCHS="美国本土外小岛屿",FullNameOfENG="United StatesMinor Outlying Islands"},
            new NationCode{ChineseAbbr="乌拉圭",EnglishAbbr="URUGUAY",TwoCharCode="UY",ThreeCharCode="URY",DigitalCode="858",FullNameOfCHS="乌拉圭东岸共和国",FullNameOfENG="Oriental Republicof Uruguay"},
            new NationCode{ChineseAbbr="乌兹别克斯坦",EnglishAbbr="UZBEKISTAN",TwoCharCode="UZ",ThreeCharCode="UZB",DigitalCode="860",FullNameOfCHS="乌兹别克斯坦共和国",FullNameOfENG="Republic ofUzbekistan"},
            new NationCode{ChineseAbbr="瓦努阿图",EnglishAbbr="VANUATU",TwoCharCode="VU",ThreeCharCode="VUT",DigitalCode="548",FullNameOfCHS="瓦努阿图共和国",FullNameOfENG="Republic of Vanuatu"},
            new NationCode{ChineseAbbr="梵蒂冈",EnglishAbbr="VATICAN",TwoCharCode="VA",ThreeCharCode="VAT",DigitalCode="336",FullNameOfCHS="梵蒂冈城国",FullNameOfENG="Vatican City State"},
            new NationCode{ChineseAbbr="委内瑞拉",EnglishAbbr="VENEZUELA",TwoCharCode="VE",ThreeCharCode="VEN",DigitalCode="862",FullNameOfCHS="委内瑞拉共和国",FullNameOfENG="Republic ofVenezuela"},
            new NationCode{ChineseAbbr="越南",EnglishAbbr="VIET NAM",TwoCharCode="VN",ThreeCharCode="VNM",DigitalCode="704",FullNameOfCHS="越南社会主席共和国",FullNameOfENG="SocialistRepublic of Viet Nam"},
            new NationCode{ChineseAbbr="英属维尔京群岛",EnglishAbbr="VIRGIN ISLANDS,BRITISH",TwoCharCode="VG",ThreeCharCode="VGB",DigitalCode="092",FullNameOfCHS="英属维尔京群岛",FullNameOfENG="British VirginIslands"},
            new NationCode{ChineseAbbr="美属维尔京群岛",EnglishAbbr="VIRGIN ISLANDS,U.S.",TwoCharCode="VI",ThreeCharCode="VIR",DigitalCode="850",FullNameOfCHS="美属维尔京群岛",FullNameOfENG="Virgin Islands ofthe United States"},
            new NationCode{ChineseAbbr="瓦利斯和富图纳",EnglishAbbr="WALLIS AND FUTUNA",TwoCharCode="WF",ThreeCharCode="WLF",DigitalCode="876",FullNameOfCHS="瓦利斯和富图纳群岛",FullNameOfENG="Wallis andFutuna"},
            new NationCode{ChineseAbbr="西撒哈拉",EnglishAbbr="WESTERN SAHARA",TwoCharCode="EH",ThreeCharCode="ESH",DigitalCode="732",FullNameOfCHS="西撒哈拉",FullNameOfENG="Western Sahara"},
            new NationCode{ChineseAbbr="也门",EnglishAbbr="YEMEN",TwoCharCode="YE",ThreeCharCode="YEM",DigitalCode="887",FullNameOfCHS="也门共和国",FullNameOfENG="Republic of Yemen"},
            new NationCode{ChineseAbbr="南斯拉夫",EnglishAbbr="YUGOSLAVIA",TwoCharCode="YU",ThreeCharCode="YUG",DigitalCode="891",FullNameOfCHS="南斯拉夫联盟共和国",FullNameOfENG="FederalRepublic of Yugoslavia"},
            new NationCode{ChineseAbbr="赞比亚",EnglishAbbr="ZAMBIA",TwoCharCode="ZM",ThreeCharCode="ZMB",DigitalCode="894",FullNameOfCHS="赞比亚共和国",FullNameOfENG="Republic of Zambia"},
            new NationCode{ChineseAbbr="津巴布韦",EnglishAbbr="ZIMBABWE",TwoCharCode="ZW",ThreeCharCode="ZWE",DigitalCode="716",FullNameOfCHS="津巴布韦共和国",FullNameOfENG="Republic ofZimbabwe"},
            #endregion
        };
        /// <summary>
        /// 中文简称
        /// </summary>
        public string ChineseAbbr { get; set; }
        /// <summary>
        /// 英文简称
        /// </summary>
        public string EnglishAbbr { get; set; }
        /// <summary>
        /// 二字符代码
        /// </summary>
        public string TwoCharCode { get; set; }
        /// <summary>
        /// 三字符代码
        /// </summary>
        public string ThreeCharCode { get; set; }
        /// <summary>
        /// 数字代码
        /// </summary>
        public string DigitalCode { get; set; }
        /// <summary>
        /// 中文全称
        /// </summary>
        public string FullNameOfCHS { get; set; }
        /// <summary>
        /// 英文全称
        /// </summary>
        public string FullNameOfENG { get; set; }
    }
}
